### ISSUE TITLE
[Bug] AbsolutePublicAPI(configuration, token) does not call this.InitializeAPIClasses

### ISSUE THREAD

**Issue by dgibso29** [AbsolutePS/AbsoluteAPI#1]
As stated. The constructor overload
`    public AbsolutePublicAPI(
      AbsolutePublicAPIConfiguration configuration,
      AbsolutePublicAPIToken token)`
Does not call InitializeAPIClasses. Since the API Classes are readonly, the component cannot be used with this constructor.

**Comment by AbsolutePS** [comment]
Thanks for the report @dgibso29 .

This has been fixed in 2.0.1 version of the library found here: https://www.nuget.org/packages/AbsolutePublicAPI/2.0.1
